name: Deployment Workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - 'release-*'

jobs:
  build_and_publish_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t docker.pkg.github.com/madetara/nyisnear/bot:1.0.$GITHUB_RUN_NUMBER .
      - name: Docker build latest
        run: docker build -t docker.pkg.github.com/madetara/nyisnear/bot:latest .
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u madetara --password-stdin
      - name: Docker publish
        run: docker push docker.pkg.github.com/madetara/nyisnear/bot:1.0.$GITHUB_RUN_NUMBER
      - name: Docker publish latest
        run: docker push docker.pkg.github.com/madetara/nyisnear/bot:latest

  deploy_image:
    runs-on: ubuntu-18.04
    needs: build_and_publish_image
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_URL: ${{ secrets.BOT_URL }}
      BOT_PORT: ${{ secrets.BOT_PORT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: BOT_TOKEN, BOT_URL, BOT_PORT, GITHUB_TOKEN, GITHUB_RUN_NUMBER
          script: |
            echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u madetara --password-stdin
            docker stop nyisnear
            docker rm nyisnear
            docker run -d --name nyisnear --restart unless-stopped -p $BOT_PORT:3000 \
              --env BOT_TOKEN="$BOT_TOKEN" \
              --env BOT_URL="$BOT_URL" \
              --env BOT_PORT="$BOT_PORT" \
              "docker.pkg.github.com/madetara/nyisnear/bot:1.0.$GITHUB_RUN_NUMBER"
