name: Deployment Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'release-*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.dockerignore'
      - '.gitignore'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/madetara/nyisnear/bot:1.0.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_image:
    runs-on: ubuntu-18.04
    needs: build_and_push
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_URL: ${{ secrets.BOT_URL }}
      BOT_PORT: ${{ secrets.BOT_PORT }}
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: BOT_TOKEN, BOT_URL, BOT_PORT, CR_PAT, GITHUB_RUN_NUMBER
          script: |
            echo $CR_PAT | podman login ghcr.io -u madetara --password-stdin
            podman stop nyisnear
            podman rm nyisnear
            podman run -d --name nyisnear --restart unless-stopped -p $BOT_PORT:3000 \
              -v "/workload/nyisnear:/data" \
              --env BOT_TOKEN="$BOT_TOKEN" \
              --env BOT_URL="$BOT_URL" \
              --env BOT_PORT="$BOT_PORT" \
              "ghcr.io/madetara/nyisnear/bot:1.0.$GITHUB_RUN_NUMBER"
